### ISSUE TITLE
[bug]: NodeJS 16 actions are deprecated forced to use Node 20

### ISSUE THREAD

**Issue by affeldt28** [srealmoreno/label-sync-action#362]
### Config file of your workflow

_N/A_

### Describe the bug

```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: srealmoreno/label-sync-action@v1.0.2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

### Expected behavior

Use NodeJS 20.

### Current behavior

Used NodeJS 16.

### Aditional information

Related: #309 

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CONTRIBUTING.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CODE_OF_CONDUCT.md).

**Comment by affeldt28** [comment]
Not Stale

**Comment by srealmoreno** [comment]
Close #363
